package com.hrms.hrms.modules.auth.dto;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RegisterResponse {

    private Long userId; // ID generated by postgreSQL
    private String username; // Registered User
    private String email; // Registered email
    private String role; // Account role
    private String status; // Account status
    private String message; // Success message
}